version: '3.1'
services:
  web:
    image: php:8.1-apache
    volumes:
      - ./src:/var/www/html:rw
    ports:
      - "8080:80"
    depends_on:
      - db
    tty: true
    stdin_open: true

  db:
    image: bitnami/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "howsecureismypasswd"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080